.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "WHONIX" "1" "April 2020" "whonix-base-files" "whonix-base-files Manual"
.SH "NAME"
\fBwhonix\fR \- Whonix Help File
.P
.SH "SYNOPSIS"
\fBwhonix\fR
.SH "DESCRIPTION"
Simply type \fIwhonix\fR in the terminal, you will see some basic facts about Whonix and command line tools, which come with Whonix\.
.SH "EXAMPLE"
\fBwhonix | more\fR
.SH "ONLINE DOCUMENTATION"
https://www\.whonix\.org
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@whonix\.org)\.
