#!/bin/bash

## Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

if test -f /usr/share/anon-gw-base-files/gateway ; then
   name=Whonix-Gateway
elif test -f /usr/share/anon-ws-base-files/workstation ; then
   name=Whonix-Workstation
elif test -f /usr/share/whonix-libvirt/marker ; then
   name=Whonix-Host
fi

echo "Welcome to $name ™!"
echo 'https://www.whonix.org

Whonix Copyright (C) 2012 - 2020 ENCRYPTED SUPPORT LP
Whonix is Freedom Software, and you are welcome to redistribute it under
certain conditions; type "whonix-license" <enter> for details.
Whonix is a compilation of software packages, each under its own copyright and
license. The exact license terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Whonix GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law; for details type "whonix-disclaimer" <enter>.

Whonix is a derivative of Debian GNU/Linux and based on Tor.

Whonix is produced independently from the Tor (r) anonymity software and
carries no guarantee from The Tor Project about quality, suitability or
anything else.

Whonix is a research project.
'

if command -v qubesdb-read >/dev/null 2>&1 ; then
   ## Skip Qubes default password until Qubes sudo gets implemented.
   ## https://github.com/QubesOS/qubes-issues/issues/2695
   true
else
   echo 'default user account: user
default password: changeme
'
fi

echo 'Type: "whonix" <enter> for help.'
